### PR TITLE
FI-942 BDT update

### PR DESCRIPTION
**Pull request by yunwwang**
Update BDT service to the latest Aug. 11th commit

### CODE REVIEW

**Comment by Jammjammjamm** [comment]
Should these all pass against the bulk data preset? I get a few errors:

Screen Shot 2020-09-08 at 1 40 03 PM

Screen Shot 2020-09-08 at 1 40 39 PM

**Comment by arscan** [comment]
I was able to update the BDT service, build it, and point this branch to it, and it seemed to work.  There were some failures against the server I was testing, but I feel like those should be addressed separately.

Also, I noticed the interface lists the requests/results backwards (that may be due to a bug that we addressed regarding request/response orders, that may not have landed in community, or may need to be updated slightly in this code?)

**Comment by arscan** [comment]
Turns our the request/response log is backwards because a fix we brought to program edition didn't make it to community. I created a jira ticket for that, I don't think we need to address here.

**Review by arscan — APPROVED** [review]
I'm good with this.  It appears the integration is working now, and we can address individual test issues separately.

**Pull request merged**
