### PR TITLE
Migrate ClinicalNotes Sequence from Program edition

### PR DESCRIPTION
**Pull request by yunwwang**
# Summary
Fix the issue reported at #551 
Migrated Clinical Notes sequences from Inferno Program to Inferno Community

## Testing guidance
Test using steps mentioned in #551

### CODE REVIEW

**Review by okeefm — APPROVED** [review]
Clinical Notes sequence looks good to me; identical to program and passes against our reference server.

**Comment by AGobron** [comment]
Hi @arscan and @okeefm, is there a timeframe on when this change will get it's second review?

**Comment by joeysad2** [comment]
@arscan and @okeefm we also would like a timeframe on when this will get a second review and therefore completed. Thanks.

**Review by Jammjammjamm — APPROVED** [review]

**Comment by joeysad2** [comment]
@yunwwang do we have a timeline on when this will be merged?

**Pull request merged**
