### PR TITLE
FI-381: Refactor launch sequences

### PR DESCRIPTION
**Pull request by Jammjammjamm**
This PR:
- refactors the launch and token refresh sequences to eliminate duplicated code
- validates that received scopes are a strict subset of the requested scopes
- updated some remaining references to US Core at `build.fhir.org` 

**Submitter:**
- [x] This pull request describes why these changes were made
- [x] Internal ticket for this PR: https://oncprojectracking.healthit.gov/support/browse/FI-381
- [x] Internal ticket links to this PR
- [x] Internal ticket is properly labeled (Community/Program)
- [x] Internal ticket has a justification for its Community/Program label
- [x] Code diff has been reviewed for extraneous/missing code
- [x] Tests are included and test edge cases
- [x] Tests/code quality metrics have been run locally and pass

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure
      where appropriate, and accomplishes the task's purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure
      where appropriate, and accomplishes the task's purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by arscan** [comment]
When I run the EHR launch against the SITE reference (https://fhir.sitenv.org/open/, login, see registered clients, launch the 'localhost' one), I get the following error:

Screen Shot 2019-12-05 at 12 03 38 PM

You may have removed some `save!` that we actually needed?  How DataMapper handles dirty resources isn't well understood, which is why we have a lot more 'saves' in there than you would otherwise think is necessary.

**Comment by Jammjammjamm** [comment]
Yeah, when I was debugging one of these issues earlier it was telling me that `@instance` had no dirty attributes and was both clean and dirty. I'll take another pass at trying to ensure that the updates are safe.

**Comment by Jammjammjamm** [comment]
Yup, that's what's happening here:
```
[1] pry(#<Inferno::Sequence::OncEHRLaunchSequence>)> @instance.clean?
=> true
[2] pry(#<Inferno::Sequence::OncEHRLaunchSequence>)> @instance.dirty?
=> true
[3] pry(#<Inferno::Sequence::OncEHRLaunchSequence>)> @instance.dirty_attributes
=> {}
```
🤷‍♂

**Comment by arscan** [comment]
Yeah, so unfortunately i think that means we don't know, so we just have to shove in a bunch of `save!` all over the place for the time being, which is really bad.  I'd love to have our db-connected models be isolated from the test runner, and then just save things off in bulk at the beginning and end of each executed test so test writers don't know to know about these types of quirks!

**Pull request merged**
